USE Omnistack
CREATE TABLE [dbo].[USER] (
    [ID] INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    [NAME] VARCHAR(50), 
    [AVATAR] VARCHAR(50),
    [URL] VARCHAR(1000),
    [BIO] VARCHAR(200),
    [LINKEDIN] VARCHAR(1000),
    [LOCATION] VARCHAR(50)
);